{% set name = "bloptools" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bloptools-{{ version }}.tar.gz
  sha256: 013b0ccc5f04ecf9afd173ee0c542dbf8c4dd73473177076e0ae87c485e9a503

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky >=1.6.1
    - botorch
    - databroker
    - gpytorch
    - matplotlib-base
    - numpy
    - ophyd
    - ortools-python
    - pytorch
    - scipy
    - sirepo-bluesky

test:
  imports:
    - bloptools
    - bloptools.bo
    - bloptools.bo.acquisition
    - bloptools.bo.kernels
    - bloptools.bo.models
    - bloptools.de
    - bloptools.de.de_opt_utils
    - bloptools.de.de_optimization
    - bloptools.de.hardware_flyer
    - bloptools.experiments
    - bloptools.experiments.atf
    - bloptools.experiments.atf.atf
    - bloptools.experiments.nsls2
    - bloptools.experiments.nsls2.iss
    - bloptools.experiments.nsls2.tes
    - bloptools.experiments.shadow
    - bloptools.experiments.shadow.chx
    - bloptools.experiments.shadow.tes
    - bloptools.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NSLS-II/bloptools
  summary: Beamline Optimization Tools
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - AbbyGi
    - thomaswmorris
    - conda-forge/event-model
